- id: 10.1093/gigascience/giz041
  image: https://raw.githubusercontent.com/BioPortainer/BioPortainer/master/images/BioPortainerWorkbench.png

- id: 10.1093/bioinformatics/btx554
  image: https://raw.githubusercontent.com/DugongBioinformatics/dugongbioinformatics.github.io/master/.misc/Dugong%20-%20images%20paper.png
