- id: 10.1093/gigascience/giz041
  image: https://www.researchgate.net/publication/332639465/figure/fig1/AS:751587882442755@1556203923996/Overview-of-the-BioPortainer-Workbench-Architecture-Users-a-can-access-the.jpg
